[package]
name = "discord_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.12.4", default-features = true }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
poise = "0.6.1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
